/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikliRouteImport } from './routes/artikli'
import { Route as GrokRouteImport } from './routes/grok'
import { Route as IzvestajiRouteImport } from './routes/izvestaji'
import { Route as KnjigovodjaRouteImport } from './routes/knjigovodja'
import { Route as KontrolaRouteImport } from './routes/kontrola'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PodesavanjaRouteImport } from './routes/podesavanja'
import { Route as PopisRouteImport } from './routes/popis'
import { Route as PorudzbineRouteImport } from './routes/porudzbine'
import { Route as ProdajaRouteImport } from './routes/prodaja'
import { Route as ProizvodnjaRouteImport } from './routes/proizvodnja'
import { Route as RacuniRouteImport } from './routes/racuni'
import { Route as RashodRouteImport } from './routes/rashod'
import { Route as ReceptureRouteImport } from './routes/recepture'
import { Route as SmeneRouteImport } from './routes/smene'
import { Route as TroskoviRouteImport } from './routes/troskovi'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDpuV1PregledRouteImport } from './routes/api/dpu/v1/pregled'
import { Route as ApiDpuV1RadnjaRouteImport } from './routes/api/dpu/v1/radnja'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikliRoute = ArtikliRouteImport.update({
  id: '/artikli',
  path: '/artikli',
  getParentRoute: () => rootRouteImport,
} as any)
const GrokRoute = GrokRouteImport.update({
  id: '/grok',
  path: '/grok',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvestajiRoute = IzvestajiRouteImport.update({
  id: '/izvestaji',
  path: '/izvestaji',
  getParentRoute: () => rootRouteImport,
} as any)
const KnjigovodjaRoute = KnjigovodjaRouteImport.update({
  id: '/knjigovodja',
  path: '/knjigovodja',
  getParentRoute: () => rootRouteImport,
} as any)
const KontrolaRoute = KontrolaRouteImport.update({
  id: '/kontrola',
  path: '/kontrola',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PodesavanjaRoute = PodesavanjaRouteImport.update({
  id: '/podesavanja',
  path: '/podesavanja',
  getParentRoute: () => rootRouteImport,
} as any)
const PopisRoute = PopisRouteImport.update({
  id: '/popis',
  path: '/popis',
  getParentRoute: () => rootRouteImport,
} as any)
const PorudzbineRoute = PorudzbineRouteImport.update({
  id: '/porudzbine',
  path: '/porudzbine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdajaRoute = ProdajaRouteImport.update({
  id: '/prodaja',
  path: '/prodaja',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodnjaRoute = ProizvodnjaRouteImport.update({
  id: '/proizvodnja',
  path: '/proizvodnja',
  getParentRoute: () => rootRouteImport,
} as any)
const RacuniRoute = RacuniRouteImport.update({
  id: '/racuni',
  path: '/racuni',
  getParentRoute: () => rootRouteImport,
} as any)
const RashodRoute = RashodRouteImport.update({
  id: '/rashod',
  path: '/rashod',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptureRoute = ReceptureRouteImport.update({
  id: '/recepture',
  path: '/recepture',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeneRoute = SmeneRouteImport.update({
  id: '/smene',
  path: '/smene',
  getParentRoute: () => rootRouteImport,
} as any)
const TroskoviRoute = TroskoviRouteImport.update({
  id: '/troskovi',
  path: '/troskovi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDpuV1PregledRoute = ApiDpuV1PregledRouteImport.update({
  id: '/api/dpu/v1/pregled',
  path: '/api/dpu/v1/pregled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDpuV1RadnjaRoute = ApiDpuV1RadnjaRouteImport.update({
  id: '/api/dpu/v1/radnja',
  path: '/api/dpu/v1/radnja',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikli': typeof ArtikliRoute
  '/grok': typeof GrokRoute
  '/izvestaji': typeof IzvestajiRoute
  '/knjigovodja': typeof KnjigovodjaRoute
  '/kontrola': typeof KontrolaRoute
  '/login': typeof LoginRoute
  '/podesavanja': typeof PodesavanjaRoute
  '/popis': typeof PopisRoute
  '/porudzbine': typeof PorudzbineRoute
  '/prodaja': typeof ProdajaRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/racuni': typeof RacuniRoute
  '/rashod': typeof RashodRoute
  '/recepture': typeof ReceptureRoute
  '/smene': typeof SmeneRoute
  '/troskovi': typeof TroskoviRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dpu/v1/pregled': typeof ApiDpuV1PregledRoute
  '/api/dpu/v1/radnja': typeof ApiDpuV1RadnjaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikli': typeof ArtikliRoute
  '/grok': typeof GrokRoute
  '/izvestaji': typeof IzvestajiRoute
  '/knjigovodja': typeof KnjigovodjaRoute
  '/kontrola': typeof KontrolaRoute
  '/login': typeof LoginRoute
  '/podesavanja': typeof PodesavanjaRoute
  '/popis': typeof PopisRoute
  '/porudzbine': typeof PorudzbineRoute
  '/prodaja': typeof ProdajaRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/racuni': typeof RacuniRoute
  '/rashod': typeof RashodRoute
  '/recepture': typeof ReceptureRoute
  '/smene': typeof SmeneRoute
  '/troskovi': typeof TroskoviRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dpu/v1/pregled': typeof ApiDpuV1PregledRoute
  '/api/dpu/v1/radnja': typeof ApiDpuV1RadnjaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikli': typeof ArtikliRoute
  '/grok': typeof GrokRoute
  '/izvestaji': typeof IzvestajiRoute
  '/knjigovodja': typeof KnjigovodjaRoute
  '/kontrola': typeof KontrolaRoute
  '/login': typeof LoginRoute
  '/podesavanja': typeof PodesavanjaRoute
  '/popis': typeof PopisRoute
  '/porudzbine': typeof PorudzbineRoute
  '/prodaja': typeof ProdajaRoute
  '/proizvodnja': typeof ProizvodnjaRoute
  '/racuni': typeof RacuniRoute
  '/rashod': typeof RashodRoute
  '/recepture': typeof ReceptureRoute
  '/smene': typeof SmeneRoute
  '/troskovi': typeof TroskoviRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dpu/v1/pregled': typeof ApiDpuV1PregledRoute
  '/api/dpu/v1/radnja': typeof ApiDpuV1RadnjaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikli'
    | '/grok'
    | '/izvestaji'
    | '/knjigovodja'
    | '/kontrola'
    | '/login'
    | '/podesavanja'
    | '/popis'
    | '/porudzbine'
    | '/prodaja'
    | '/proizvodnja'
    | '/racuni'
    | '/rashod'
    | '/recepture'
    | '/smene'
    | '/troskovi'
    | '/api/auth/$'
    | '/api/dpu/v1/pregled'
    | '/api/dpu/v1/radnja'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikli'
    | '/grok'
    | '/izvestaji'
    | '/knjigovodja'
    | '/kontrola'
    | '/login'
    | '/podesavanja'
    | '/popis'
    | '/porudzbine'
    | '/prodaja'
    | '/proizvodnja'
    | '/racuni'
    | '/rashod'
    | '/recepture'
    | '/smene'
    | '/troskovi'
    | '/api/auth/$'
    | '/api/dpu/v1/pregled'
    | '/api/dpu/v1/radnja'
  id:
    | '__root__'
    | '/'
    | '/artikli'
    | '/grok'
    | '/izvestaji'
    | '/knjigovodja'
    | '/kontrola'
    | '/login'
    | '/podesavanja'
    | '/popis'
    | '/porudzbine'
    | '/prodaja'
    | '/proizvodnja'
    | '/racuni'
    | '/rashod'
    | '/recepture'
    | '/smene'
    | '/troskovi'
    | '/api/auth/$'
    | '/api/dpu/v1/pregled'
    | '/api/dpu/v1/radnja'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikliRoute: typeof ArtikliRoute
  GrokRoute: typeof GrokRoute
  IzvestajiRoute: typeof IzvestajiRoute
  KnjigovodjaRoute: typeof KnjigovodjaRoute
  KontrolaRoute: typeof KontrolaRoute
  LoginRoute: typeof LoginRoute
  PodesavanjaRoute: typeof PodesavanjaRoute
  PopisRoute: typeof PopisRoute
  PorudzbineRoute: typeof PorudzbineRoute
  ProdajaRoute: typeof ProdajaRoute
  ProizvodnjaRoute: typeof ProizvodnjaRoute
  RacuniRoute: typeof RacuniRoute
  RashodRoute: typeof RashodRoute
  ReceptureRoute: typeof ReceptureRoute
  SmeneRoute: typeof SmeneRoute
  TroskoviRoute: typeof TroskoviRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDpuV1PregledRoute: typeof ApiDpuV1PregledRoute
  ApiDpuV1RadnjaRoute: typeof ApiDpuV1RadnjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikli': {
      id: '/artikli'
      path: '/artikli'
      fullPath: '/artikli'
      preLoaderRoute: typeof ArtikliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grok': {
      id: '/grok'
      path: '/grok'
      fullPath: '/grok'
      preLoaderRoute: typeof GrokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvestaji': {
      id: '/izvestaji'
      path: '/izvestaji'
      fullPath: '/izvestaji'
      preLoaderRoute: typeof IzvestajiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knjigovodja': {
      id: '/knjigovodja'
      path: '/knjigovodja'
      fullPath: '/knjigovodja'
      preLoaderRoute: typeof KnjigovodjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontrola': {
      id: '/kontrola'
      path: '/kontrola'
      fullPath: '/kontrola'
      preLoaderRoute: typeof KontrolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podesavanja': {
      id: '/podesavanja'
      path: '/podesavanja'
      fullPath: '/podesavanja'
      preLoaderRoute: typeof PodesavanjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popis': {
      id: '/popis'
      path: '/popis'
      fullPath: '/popis'
      preLoaderRoute: typeof PopisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porudzbine': {
      id: '/porudzbine'
      path: '/porudzbine'
      fullPath: '/porudzbine'
      preLoaderRoute: typeof PorudzbineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodaja': {
      id: '/prodaja'
      path: '/prodaja'
      fullPath: '/prodaja'
      preLoaderRoute: typeof ProdajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodnja': {
      id: '/proizvodnja'
      path: '/proizvodnja'
      fullPath: '/proizvodnja'
      preLoaderRoute: typeof ProizvodnjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racuni': {
      id: '/racuni'
      path: '/racuni'
      fullPath: '/racuni'
      preLoaderRoute: typeof RacuniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rashod': {
      id: '/rashod'
      path: '/rashod'
      fullPath: '/rashod'
      preLoaderRoute: typeof RashodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepture': {
      id: '/recepture'
      path: '/recepture'
      fullPath: '/recepture'
      preLoaderRoute: typeof ReceptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smene': {
      id: '/smene'
      path: '/smene'
      fullPath: '/smene'
      preLoaderRoute: typeof SmeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troskovi': {
      id: '/troskovi'
      path: '/troskovi'
      fullPath: '/troskovi'
      preLoaderRoute: typeof TroskoviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dpu/v1/pregled': {
      id: '/api/dpu/v1/pregled'
      path: '/api/dpu/v1/pregled'
      fullPath: '/api/dpu/v1/pregled'
      preLoaderRoute: typeof ApiDpuV1PregledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dpu/v1/radnja': {
      id: '/api/dpu/v1/radnja'
      path: '/api/dpu/v1/radnja'
      fullPath: '/api/dpu/v1/radnja'
      preLoaderRoute: typeof ApiDpuV1RadnjaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikliRoute: ArtikliRoute,
  GrokRoute: GrokRoute,
  IzvestajiRoute: IzvestajiRoute,
  KnjigovodjaRoute: KnjigovodjaRoute,
  KontrolaRoute: KontrolaRoute,
  LoginRoute: LoginRoute,
  PodesavanjaRoute: PodesavanjaRoute,
  PopisRoute: PopisRoute,
  PorudzbineRoute: PorudzbineRoute,
  ProdajaRoute: ProdajaRoute,
  ProizvodnjaRoute: ProizvodnjaRoute,
  RacuniRoute: RacuniRoute,
  RashodRoute: RashodRoute,
  ReceptureRoute: ReceptureRoute,
  SmeneRoute: SmeneRoute,
  TroskoviRoute: TroskoviRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDpuV1PregledRoute: ApiDpuV1PregledRoute,
  ApiDpuV1RadnjaRoute: ApiDpuV1RadnjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
